### ISSUE TITLE
Reporte de práctica

### ISSUE THREAD

**Issue by IsraelNicolas61** [SistemasTecTlaxiaco/practica-final-de-hilos-equipo-vaii#2]
[reporte practica final Hilos.pdf](https://github.com/SistemasTecTlaxiaco/practica-final-de-hilos-equipo-vaii/files/6516377/reporte.practica.final.Hilos.pdf)

**Comment by Band-hi** [comment]
Puntaje: 97/100 
Calificación: 19.4

Muy buen trabajo, solamente falto agregar la lista de figuras

**Comment by josealfredo79** [comment]
Bien hecho y revisado
